services:
  moodbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # 환경 변수 설정 (.env 파일에서 로드)
      - HF_TOKEN=${HF_TOKEN}
      - HF_MODEL_ID=${HF_MODEL_ID:-JaeJiMin/daily_hug}
      - HF_MAX_TOKENS=${HF_MAX_TOKENS:-512}
      - HF_TEMPERATURE=${HF_TEMPERATURE:-0.7}
      - HF_TIMEOUT=${HF_TIMEOUT:-30}
      - ENV=${ENV:-prod}
    volumes:
      # 데이터베이스 영속성 보장
      - ./diary.db:/app/diary.db
      # 모델 캐시 저장 (재시작 시 재다운로드 방지)
      - huggingface-cache:/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # 리소스 제한 (필요에 따라 조정)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

volumes:
  huggingface-cache:
    driver: local
